behaviors:
  FoxAgent:                                 # MUST match Behavior Name in Unity
    trainer_type: ppo

    # -------------------- Hyperparameters --------------------
    hyperparameters:
      batch_size: 4096
      buffer_size: 65536
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear

    # -------------------- Network --------------------
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: resnet
      memory:
        sequence_length: 64
        memory_size: 128
      # Make sure your Behavior actually has visual observations enabled in Unity

    # -------------------- Reward signals --------------------
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        learning_rate: 1.0e-3
        network_settings:            # replaced deprecated `encoding_size`
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple

    # -------------------- Optional: Behavioral Cloning --------------------
    behavioral_cloning:
      demo_path: 'Y:/Drive/My_Drive/folder/UU/Ai_for_games_proj/Python/Demos_high_g/'
      strength: 0.55
      steps: 150000000

    # -------------------- Training cadence / logging --------------------
    max_steps: 5.0e6
    time_horizon: 128
    summary_freq: 5000
    keep_checkpoints: 3

    # -------------------- Init from checkpoint (pretrain -> finetune) --------------------
    init_path: 'Y:/Drive/My_Drive/folder/UU/Ai_for_games_proj/Python/FoxAgent_stable_base.pt'

# -------------------- Engine / device --------------------
torch_settings:
  device: cuda

# -------------------- Optional: Curriculum --------------------
# environment_parameters:
#   difficulty:
#     curriculum:
#       - name: easy
#         completion_criteria:
#           measure: reward
#           behavior: FoxAgent
#           signal_smoothing: true
#           min_lesson_length: 200
#           threshold: 0.7
#         value: 0
#       - name: medium
#         completion_criteria:
#           measure: reward
#           behavior: FoxAgent
#           signal_smoothing: true
#           min_lesson_length: 200
#           threshold: 1.2
#         value: 1
#       - name: hard
#         value: 2
