behaviors:
  FoxAgent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 4096
      buffer_size: 32768
      learning_rate: 1.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: resnet
      memory:
        sequence_length: 256
        memory_size: 128

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

    behavioral_cloning:
      demo_path: 'Y:/Drive/My_Drive/folder/UU/Ai_for_games_proj/Python/Demos_high_g/'
      strength: 0.10
      steps: 300000
      samples_per_update: 0

    max_steps: 5.0e7
    time_horizon: 256
    summary_freq: 5000
    keep_checkpoints: 15

    init_path: 'Y:/Drive/My_Drive/folder/UU/Ai_for_games_proj/Python/results/fox6_par3_exploit_ft/FoxAgent/FoxAgent-6210314.pt'

torch_settings:
  device: cuda
